import { UserRole } from 'src/enums/UserRole.enum';

export const data = [
  {
    name: 'Edu Cardi',
    email: 'edu@mail.com',
    password: 'Secure123*',
    phone: 8443323211,
    address: 'Avenida Siempre Viva 123',
    role: UserRole.SUPERADMIN,
  },
  {
    name: 'Mati Pinilla',
    email: 'mati@mail.com',
    password: 'Secure123*',
    phone: 3165278156,
    address: 'Boulevard Siempre Vivo 123',
    role: UserRole.SUPERADMIN,
  },
  {
    name: 'Lean Gianelli',
    email: 'lean@mail.com',
    password: 'Secure123*',
    phone: 8443323851,
    address: 'Calle Siempre Feliz 123',
    role: UserRole.SUPERADMIN,
  },
  {
    name: 'Santy Taborda',
    email: 'santy@mail.com',
    password: 'Secure123*',
    phone: 5643323211,
    address: 'Avenida Siempre Joven 123',
    role: UserRole.SUPERADMIN,
  },
  {
    name: 'Pedro Pan',
    email: 'pedro@mail.com',
    password: 'Secure123*',
    phone: 1234523211,
    address: 'Avenida Siempre Migrado 123',
    role: UserRole.ADMIN,
  },
  {
    name: 'Omar En El Mar',
    email: 'omar@mail.com',
    password: 'Secure123*',
    phone: 1234567890,
    address: 'Avenida Siempre Migrado 123',
    role: UserRole.ADMIN,
  },
  {
    name: 'Daniel Positive',
    email: 'daniel@mail.com',
    password: 'Secure123*',
    phone: 9876543210,
    address: 'Avenida Siempre Viva 123',
    role: UserRole.ADMIN,
  },
  {
    name: 'Ana Torres',
    email: 'torres1@mail.com',
    password: 'Secure123*',
    phone: 3210000001,
    address: 'Calle Olivo 101',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Luis García',
    email: 'garcia2@mail.com',
    password: 'Secure123*',
    phone: 3210000002,
    address: 'Calle Olmo 102',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'María Pérez',
    email: 'perez3@mail.com',
    password: 'Secure123*',
    phone: 3210000003,
    address: 'Calle Abeto 103',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Carlos Ruiz',
    email: 'ruiz4@mail.com',
    password: 'Secure123*',
    phone: 3210000004,
    address: 'Calle Fresno 104',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Sofía Herrera',
    email: 'herrera5@mail.com',
    password: 'Secure123*',
    phone: 3210000005,
    address: 'Calle Sauce 105',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Mateo López',
    email: 'lopez6@mail.com',
    password: 'Secure123*',
    phone: 3210000006,
    address: 'Calle Laurel 106',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Camila Castro',
    email: 'castro7@mail.com',
    password: 'Secure123*',
    phone: 3210000007,
    address: 'Calle Cedro 107',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Javier Díaz',
    email: 'diaz8@mail.com',
    password: 'Secure123*',
    phone: 3210000008,
    address: 'Calle Pino 108',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Valentina Gómez',
    email: 'gomez9@mail.com',
    password: 'Secure123*',
    phone: 3210000009,
    address: 'Calle Roble 109',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Diego Molina',
    email: 'molina10@mail.com',
    password: 'Secure123*',
    phone: 3210000010,
    address: 'Calle Ciprés 110',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Isabella Romero',
    email: 'romero11@mail.com',
    password: 'Secure123*',
    phone: 3210000011,
    address: 'Calle Jacaranda 111',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Andrés Méndez',
    email: 'mendez12@mail.com',
    password: 'Secure123*',
    phone: 3210000012,
    address: 'Calle Cerezo 112',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Renata Vargas',
    email: 'vargas13@mail.com',
    password: 'Secure123*',
    phone: 3210000013,
    address: 'Calle Almendro 113',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Tomás Ortega',
    email: 'ortega14@mail.com',
    password: 'Secure123*',
    phone: 3210000014,
    address: 'Calle Haya 114',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Paula Silva',
    email: 'silva15@mail.com',
    password: 'Secure123*',
    phone: 3210000015,
    address: 'Calle Encina 115',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Emiliano Navarro',
    email: 'navarro16@mail.com',
    password: 'Secure123*',
    phone: 3210000016,
    address: 'Calle Tejo 116',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Lucía Ramos',
    email: 'ramos17@mail.com',
    password: 'Secure123*',
    phone: 3210000017,
    address: 'Calle Acacia 117',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Gabriel Ibáñez',
    email: 'ibanez18@mail.com',
    password: 'Secure123*',
    phone: 3210000018,
    address: 'Calle Magnolia 118',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Julia Cordero',
    email: 'cordero19@mail.com',
    password: 'Secure123*',
    phone: 3210000019,
    address: 'Calle Azahar 119',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Sebastián Flores',
    email: 'flores20@mail.com',
    password: 'Secure123*',
    phone: 3210000020,
    address: 'Calle Níspero 120',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Emma León',
    email: 'leon21@mail.com',
    password: 'Secure123*',
    phone: 3210000021,
    address: 'Calle Granada 121',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'David Peña',
    email: 'pena22@mail.com',
    password: 'Secure123*',
    phone: 3210000022,
    address: 'Calle Durazno 122',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Martina Salas',
    email: 'salas23@mail.com',
    password: 'Secure123*',
    phone: 3210000023,
    address: 'Calle Peral 123',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Álvaro Montes',
    email: 'montes24@mail.com',
    password: 'Secure123*',
    phone: 3210000024,
    address: 'Calle Limonero 124',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Mía Fuentes',
    email: 'fuentes25@mail.com',
    password: 'Secure123*',
    phone: 3210000025,
    address: 'Calle Manzano 125',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Alejandro Ríos',
    email: 'rios26@mail.com',
    password: 'Secure123*',
    phone: 3210000026,
    address: 'Calle Mango 126',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Victoria Soto',
    email: 'soto27@mail.com',
    password: 'Secure123*',
    phone: 3210000027,
    address: 'Calle Papayo 127',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Santiago Lara',
    email: 'lara28@mail.com',
    password: 'Secure123*',
    phone: 3210000028,
    address: 'Calle Sandía 128',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Nicole Barrios',
    email: 'barrios29@mail.com',
    password: 'Secure123*',
    phone: 3210000029,
    address: 'Calle Higuera 129',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Bruno Aguirre',
    email: 'aguirre30@mail.com',
    password: 'Secure123*',
    phone: 3210000030,
    address: 'Calle Castaño 130',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Daniela Campos',
    email: 'campos31@mail.com',
    password: 'Secure123*',
    phone: 3210000031,
    address: 'Calle Nogal 131',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Marco Rivera',
    email: 'rivera32@mail.com',
    password: 'Secure123*',
    phone: 3210000032,
    address: 'Calle Guayabo 132',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Natalia Acosta',
    email: 'acosta33@mail.com',
    password: 'Secure123*',
    phone: 3210000033,
    address: 'Calle Lima 133',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Fernando Paredes',
    email: 'paredes34@mail.com',
    password: 'Secure123*',
    phone: 3210000034,
    address: 'Calle Mandarina 134',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Sara Núñez',
    email: 'nunez35@mail.com',
    password: 'Secure123*',
    phone: 3210000035,
    address: 'Calle Pomelo 135',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Rodrigo Valdés',
    email: 'valdes36@mail.com',
    password: 'Secure123*',
    phone: 3210000036,
    address: 'Calle Chabacano 136',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Elena Espinoza',
    email: 'espinoza37@mail.com',
    password: 'Secure123*',
    phone: 3210000037,
    address: 'Calle Avellano 137',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Iván Cabrera',
    email: 'cabrera38@mail.com',
    password: 'Secure123*',
    phone: 3210000038,
    address: 'Calle Tamarindo 138',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Laura Mejía',
    email: 'mejia39@mail.com',
    password: 'Secure123*',
    phone: 3210000039,
    address: 'Calle Ciruelo 139',
    role: UserRole.CUSTOMER,
  },
  {
    name: 'Ángela Molina',
    email: 'molina40@mail.com',
    password: 'Secure123*',
    phone: 3210000040,
    address: 'Calle Litchi 140',
    role: UserRole.CUSTOMER,
  },
];
